# Single Asset

Consider an agent performing optimal execution within a time interval $\mathbb{T}_N$, specifically over a time window $[0,T]$ divided into $N$ equally spaced intervals of length $\tau = T/N$. For a single asset to be sold (or bought), with an initial quantity $q_0$, the return $(y_t = S_{t+1} - S_{t})$ evolves according to:

$$ x_{t+1} = A_tx_{t} + B_tu_t + \omega_t $$
$$ y_t = C_tx_t + D_t u_t$$

where $x_t$ represents the permanent impact at time $t \in \mathbb{T}_N$, $\omega_t$ is a general noise term, and $u_t$ denotes the volume sold at time $t \in \mathbb{T}_N$ (note: $\sum_{t \in \mathbb{T}_N} u_t = q_0$).

The coefficients $A_t, B_t, C_t, D_t$ are defined as follows:
- $A_t$: parameter for the memory of the autoregressive permanent impact,
- $B_t$: intensity parameter of the control on impact,
- $C_t$: intensity of cross-impact,
- $D_t$: temporary impact.

To determine an optimal policy $\Pi: \mathbb{R} \to \mathbb{R}$, the agent needs to estimate these autoregressive coefficients accurately.

Estimation/action steps:
1. Filter the coefficients
2. Take action
3. Minimise loss
4. Backprop
5. Weights adj. 

## Environment

In [4]:
import ambiente as amb
import numpy as np

price_0 = 0.01
T = 10
n = 2
imp_0 = np.ones((n)) * 0.001
A_0 = np.ones((n,n)) * np.random.rand(n, n) * 0.0001
B_0 = np.ones((n,n)) * np.random.rand(n, n) * 0.0002
C_0 = np.ones((n,n)) * np.random.rand(n, n) * 0.0003
D_0 = np.ones((n,n)) * np.random.rand(n, n) * 0.0004
y_0 = np.ones((n,n)) * 0.01
u_t = np.zeros(n)

ritorni = np.zeros((n, T))
imp = []

pri = amb.Price(price_0, imp_0, A_0, B_0, C_0, D_0, y_0, u_t, N_assets = n)

for t in range(T):
    u_t = np.random.uniform(low=0.0, high=10.0, size=n)
    ritorni[..., t], impact = pri.get_price_ret(u_t)
    imp.append(impact)

ritorni, imp

(array([[0.00339627, 0.00206079, 0.00285387, 0.00203095, 0.00315108,
         0.00306531, 0.00309748, 0.00250059, 0.0030909 , 0.00256512],
        [0.00338293, 0.00092143, 0.00177422, 0.00307709, 0.00369147,
         0.00271848, 0.00313197, 0.00270608, 0.00297331, 0.00106612]]),
 [array([0.00159622, 0.00226153]),
  array([0.00052699, 0.00115451]),
  array([0.00092405, 0.0016946 ]),
  array([0.00136632, 0.00155543]),
  array([0.00169695, 0.00220475]),
  array([0.00131011, 0.00197676]),
  array([0.00147414, 0.00207161]),
  array([0.00125952, 0.00170665]),
  array([0.00141162, 0.00203793]),
  array([0.00062429, 0.00142143])])